// Representative seaport per country, used for custom start/destination selection.
export type Country = { code: string; name: string; port: string; lat: number; lng: number };

export const COUNTRIES: Country[] = [
  { code: "IN", name: "India", port: "Mumbai", lat: 18.95, lng: 72.84 },
  { code: "US", name: "United States", port: "New York", lat: 40.5, lng: -74.0 },
  { code: "CN", name: "China", port: "Shanghai", lat: 31.23, lng: 121.47 },
  { code: "SG", name: "Singapore", port: "Singapore", lat: 1.29, lng: 103.85 },
  { code: "AE", name: "United Arab Emirates", port: "Jebel Ali", lat: 25.01, lng: 55.06 },
  { code: "GB", name: "United Kingdom", port: "Felixstowe", lat: 51.95, lng: 1.3 },
  { code: "NL", name: "Netherlands", port: "Rotterdam", lat: 51.95, lng: 4.14 },
  { code: "DE", name: "Germany", port: "Hamburg", lat: 53.54, lng: 9.98 },
  { code: "JP", name: "Japan", port: "Yokohama", lat: 35.44, lng: 139.64 },
  { code: "KR", name: "South Korea", port: "Busan", lat: 35.1, lng: 129.04 },
  { code: "HK", name: "Hong Kong", port: "Hong Kong", lat: 22.3, lng: 114.18 },
  { code: "MY", name: "Malaysia", port: "Port Klang", lat: 3.0, lng: 101.39 },
  { code: "TH", name: "Thailand", port: "Laem Chabang", lat: 13.08, lng: 100.88 },
  { code: "VN", name: "Vietnam", port: "Ho Chi Minh City", lat: 10.76, lng: 106.7 },
  { code: "ID", name: "Indonesia", port: "Jakarta", lat: -6.1, lng: 106.88 },
  { code: "AU", name: "Australia", port: "Sydney", lat: -33.86, lng: 151.21 },
  { code: "NZ", name: "New Zealand", port: "Auckland", lat: -36.84, lng: 174.77 },
  { code: "ZA", name: "South Africa", port: "Cape Town", lat: -33.92, lng: 18.42 },
  { code: "EG", name: "Egypt", port: "Port Said", lat: 31.26, lng: 32.3 },
  { code: "SA", name: "Saudi Arabia", port: "Jeddah", lat: 21.48, lng: 39.19 },
  { code: "BR", name: "Brazil", port: "Santos", lat: -23.96, lng: -46.33 },
  { code: "AR", name: "Argentina", port: "Buenos Aires", lat: -34.6, lng: -58.37 },
  { code: "CL", name: "Chile", port: "Valparaíso", lat: -33.04, lng: -71.63 },
  { code: "MX", name: "Mexico", port: "Veracruz", lat: 19.2, lng: -96.14 },
  { code: "CA", name: "Canada", port: "Vancouver", lat: 49.29, lng: -123.11 },
  { code: "FR", name: "France", port: "Le Havre", lat: 49.49, lng: 0.11 },
  { code: "ES", name: "Spain", port: "Algeciras", lat: 36.13, lng: -5.45 },
  { code: "IT", name: "Italy", port: "Genoa", lat: 44.4, lng: 8.92 },
  { code: "GR", name: "Greece", port: "Piraeus", lat: 37.94, lng: 23.65 },
  { code: "TR", name: "Türkiye", port: "Istanbul", lat: 41.01, lng: 28.98 },
  { code: "PT", name: "Portugal", port: "Lisbon", lat: 38.7, lng: -9.14 },
  { code: "BE", name: "Belgium", port: "Antwerp", lat: 51.26, lng: 4.4 },
  { code: "SE", name: "Sweden", port: "Gothenburg", lat: 57.69, lng: 11.87 },
  { code: "NO", name: "Norway", port: "Oslo", lat: 59.9, lng: 10.75 },
  { code: "RU", name: "Russia", port: "St. Petersburg", lat: 59.9, lng: 30.26 },
  { code: "PL", name: "Poland", port: "Gdańsk", lat: 54.36, lng: 18.66 },
  { code: "PK", name: "Pakistan", port: "Karachi", lat: 24.84, lng: 66.99 },
  { code: "BD", name: "Bangladesh", port: "Chittagong", lat: 22.31, lng: 91.8 },
  { code: "LK", name: "Sri Lanka", port: "Colombo", lat: 6.95, lng: 79.84 },
  { code: "PH", name: "Philippines", port: "Manila", lat: 14.58, lng: 120.96 },
  { code: "TW", name: "Taiwan", port: "Kaohsiung", lat: 22.62, lng: 120.28 },
  { code: "NG", name: "Nigeria", port: "Lagos", lat: 6.44, lng: 3.42 },
  { code: "KE", name: "Kenya", port: "Mombasa", lat: -4.04, lng: 39.67 },
  { code: "MA", name: "Morocco", port: "Tangier", lat: 35.79, lng: -5.81 },
  { code: "QA", name: "Qatar", port: "Hamad", lat: 24.98, lng: 51.6 },
  { code: "OM", name: "Oman", port: "Salalah", lat: 16.94, lng: 54.0 },
  { code: "PA", name: "Panama", port: "Balboa", lat: 8.95, lng: -79.57 },
  { code: "CO", name: "Colombia", port: "Cartagena", lat: 10.4, lng: -75.51 },
  { code: "PE", name: "Peru", port: "Callao", lat: -12.05, lng: -77.15 },
].sort((a, b) => a.name.localeCompare(b.name));

export const portByCode = (code: string): Country | undefined => COUNTRIES.find((c) => c.code === code);
